Parameters:
  Tag:
    Type: String
    Default: latest

  SimpleAppDesiredCount:
    Type: Number
    Default: 2

  LoadTestDesiredCount:
    Type: Number
    Default: 0

  TargetGroup:
    Type: String

  Cluster:
    Type: String


Resources:
  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ecs-service-${AWS::StackName}
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole

  Repository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain

  Service-simple-app:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      Role: !Ref ECSServiceRole
      DesiredCount: !Ref SimpleAppDesiredCount
      TaskDefinition: !Ref TaskDefinition-simple-app
      LoadBalancers:
        - ContainerName: simple-app
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGroup

  Service-load-test:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      Role: !Ref ECSServiceRole
      DesiredCount: !Ref AbAgentDesiredCount
      TaskDefinition: !Ref TaskDefinition-ab-agent

  TaskDefinition-simple-app:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-simple-app
      ContainerDefinitions:
        - Name: simple-app
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}:${Tag}
          Essential: true
          Memory: 128
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: Tag
              Value: !Ref Tag

  TaskDefinition-load-test:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-load-test
      ContainerDefinitions:
        - Name: ab-agent
          Image: 640175474045.dkr.ecr.us-east-1.amazonaws.com/ab-agent:latest
          Essential: true
          Memory: 128
          EntryPoint: ["/usr/bin/ab"]
          Command: []
          Environment:
            - Name: Tag
              Value: !Ref Tag

Outputs:
  Repository:
    Value: !Ref Repository

  StackName:
    Value: !Ref AWS::StackName
